---
- name: ZFSOnLinux repo package installed (RedHat)
  yum:
    name: http://download.zfsonlinux.org/epel/zfs-release.el{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: ZFSOnLinux GPG key imported (RedHat)
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
    state: present

- name: ZFSforLinux repo is templated (RedHat)
  template:
    src: zfs.repo.j2
    dest: /etc/yum.repos.d/sssd.conf
    owner: root
    group: root
    mode: 0600
  register: zfs_repo_template

- name: remove old zfs kernel modules
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - zfs
    - zfs-kmod
    - spl
    - spl-kmod
    - libzfs2
    - libnvpair1
    - libuutil1
    - libzpool2
    - zfs-release
  ignore_errors: yes
  when: zfs_repo_template.changed
  
- name: kernel-devel installed if using zfs-dkms (RedHat)
  yum:
    name: kernel-devel
    state: latest
  when: zfs_dkms_el_enabled == 1
  
- name: ZFS installed (RedHat)
  yum:
    name: zfs
    state: latest
  notify: zfs_installed
...
